'use client';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { ArrowRight,ArrowUpRight,Bot,Calculator,CheckCircle2,CircleDollarSign,Copy,Delete,QrCode,RotateCw,ScanLine,Wallet,X } from 'lucide-react';
import Image from 'next/image';

type Payment={id:string;amount:string;recipient:string;description:string;network:'devnet'|'mainnet-beta';networkId:string;status:'pending'|'paid'|'expired'|'failed';createdAt:string;interfaces?:{solanaPay:string;x402?:string;x402Legacy?:string;x402Unavailable?:string};signature?:string;monitoringError?:string};
const compact=(v:string)=>`${v.slice(0,5)}…${v.slice(-5)}`;
function extractRecipient(value:string){const raw=value.trim();let candidate=raw;try{const url=new URL(raw);if(url.protocol==='solana:')candidate=url.pathname}catch{}if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(candidate))throw new Error('The QR does not contain a valid Solana address.');return candidate}

export default function Home(){
 const [amount,setAmount]=useState('25.00'); const [recipient,setRecipient]=useState(''); const [description,setDescription]=useState(''); const [expiresInSeconds,setExpiresInSeconds]=useState(86400); const [network,setNetwork]=useState<Payment['network']>('mainnet-beta'); const [developerMode,setDeveloperMode]=useState(false); const [apiKey,setApiKey]=useState(''); const [authRequired,setAuthRequired]=useState(false); const [formError,setFormError]=useState(''); const [submitting,setSubmitting]=useState(false); const [payment,setPayment]=useState<Payment|null>(null); const [copied,setCopied]=useState<string|null>(null); const [keypadOpen,setKeypadOpen]=useState(false); const [scannerOpen,setScannerOpen]=useState(false); const [scannerError,setScannerError]=useState(''); const videoRef=useRef<HTMLVideoElement>(null); const scannerRef=useRef<{stop:()=>void;destroy:()=>void}|null>(null);
 const solanaPayUrl=useMemo(()=>payment?.interfaces?.solanaPay??'',[payment]);
 async function getApiKey(){if(apiKey.trim()){sessionStorage.setItem('salmon_api_key',apiKey.trim());return apiKey.trim()}const cached=sessionStorage.getItem('salmon_api_key');if(cached)return cached;const response=await fetch('/api/auth/bootstrap',{method:'POST'});if(!response.ok){setAuthRequired(true);throw new Error('Connect a valid API key to create payment requests.')}const body=await response.json();sessionStorage.setItem('salmon_api_key',body.data.key);return body.data.key as string}
 async function createPayment(e:FormEvent){e.preventDefault();setFormError('');setSubmitting(true);try{const paymentNetwork=developerMode?network:'mainnet-beta',payload=JSON.stringify({amount,recipient,description,network:paymentNetwork,expiresInSeconds}),send=(key:string)=>fetch('/api/payment-requests',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:payload});let key=await getApiKey(),response=await send(key);if(response.status===401&&!apiKey.trim()){sessionStorage.removeItem('salmon_api_key');key=await getApiKey();response=await send(key)}const body=await response.json();if(!response.ok){if(response.status===401)setAuthRequired(true);throw new Error(body.error?.message??'Unable to create this payment request.')}const detail=await fetch(`/api/payment-requests/${body.data.id}`,{cache:'no-store'}),full=await detail.json();if(!detail.ok)throw new Error(full.error?.message??'Unable to load this payment request.');setPayment(full.data)}catch(error){setFormError(error instanceof Error?error.message:'Unable to create this payment request.')}finally{setSubmitting(false)}}
 const paymentId=payment?.id,paymentStatus=payment?.status;
 useEffect(()=>{if(!paymentId||paymentStatus!=='pending')return;const timer=window.setInterval(async()=>{const response=await fetch(`/api/payment-requests/${paymentId}`,{cache:'no-store'});if(response.ok){const body=await response.json();setPayment(body.data)}},4000);return()=>window.clearInterval(timer)},[paymentId,paymentStatus]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const enabled=localStorage.getItem('salmon_developer_mode')==='true';setDeveloperMode(enabled);if(!enabled)setNetwork('mainnet-beta')},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(!scannerOpen)return;let cancelled=false;void import('qr-scanner').then(({default:QrScanner})=>{if(cancelled||!videoRef.current)return;const scanner=new QrScanner(videoRef.current,result=>{try{setRecipient(extractRecipient(typeof result==='string'?result:result.data));setScannerOpen(false)}catch(error){setScannerError(error instanceof Error?error.message:'Invalid QR code.')}},{preferredCamera:'environment',returnDetailedScanResult:true,highlightScanRegion:true,highlightCodeOutline:true});scannerRef.current=scanner;scanner.start().catch(error=>setScannerError(error instanceof Error?error.message:'Camera access failed.'))});return()=>{cancelled=true;scannerRef.current?.stop();scannerRef.current?.destroy();scannerRef.current=null}},[scannerOpen]);
 function pressAmount(key:string){if(key==='clear'){setAmount('');return}if(key==='backspace'){setAmount(value=>value.slice(0,-1));return}setAmount(value=>{if(key===','&&(value.includes(',')||value.includes('.')))return value;if(key!==','&&/[.,]\d{6}$/.test(value))return value;if(value==='0'&&key!==',')return key;return value+key})}
 async function copy(label:string,value:string){await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(null),1400)}
 return <main>
  <nav className="nav"><a className="brand" href="#top"><span className="mark"><Image src="/icons/192/eEVdT.png" alt="" width={34} height={34}/></span><span>salmon<span className="brand-light">pay</span></span></a><div className="nav-center"><span className="live-dot"/> {developerMode?`Developer mode · ${network==='devnet'?'Devnet':'Mainnet'}`:'Solana Mainnet'}</div><a className="nav-button" href="/docs">Read the API <ArrowUpRight size={16}/></a></nav>
  <section className="hero" id="top"><div className="eyebrow"><span>Universal payment requests</span><i/></div><h1>One payment.<br/><em>Any caller.</em></h1><p>Create a USDC request once. Humans pay by QR. Compatible agents pay over HTTP. Both settle on Solana.</p></section>
  <section className="workspace">
   <div className="builder-panel"><div className="panel-heading"><div><span className="step">01</span><h2>Build a request</h2></div><span className="secure">No custody · No contract</span></div>
    <form onSubmit={createPayment}><label>Amount</label><div className="amount-field"><span>$</span><input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} aria-label="Amount"/><b>USDC</b><button className="field-action" type="button" aria-expanded={keypadOpen} onClick={()=>setKeypadOpen(value=>!value)}><Calculator size={17}/><span>Keypad</span></button></div>
     {keypadOpen&&<div className="amount-keypad" aria-label="Amount keypad">{['1','2','3','4','5','6','7','8','9',',','0','backspace'].map(key=><button type="button" key={key} onClick={()=>pressAmount(key)} aria-label={key==='backspace'?'Delete last digit':key}>{key==='backspace'?<Delete size={20}/>:key}</button>)}<button type="button" className="keypad-clear" onClick={()=>pressAmount('clear')}>Clear</button><button type="button" className="keypad-done" onClick={()=>setKeypadOpen(false)}>Done</button></div>}
     <div className={developerMode?'field-grid':'field-grid production-fields'}>{developerMode&&<div><label htmlFor="network">Network</label><select id="network" value={network} onChange={e=>setNetwork(e.target.value as Payment['network'])}><option value="devnet">Solana Devnet</option><option value="mainnet-beta">Solana Mainnet</option></select></div>}<div><label htmlFor="expiration">Expires</label><select id="expiration" value={expiresInSeconds} onChange={e=>setExpiresInSeconds(Number(e.target.value))}><option value={86400}>24 hours</option><option value={3600}>1 hour</option><option value={604800}>7 days</option></select></div></div>
     <label>Receive at</label><div className="text-field"><span className="wallet-icon"><Wallet size={18}/></span><input required value={recipient} onChange={e=>setRecipient(e.target.value)} aria-label="Recipient wallet"/><button className="field-action scan-action" type="button" onClick={()=>{setScannerError('');setScannerOpen(true)}}><ScanLine size={18}/><span>Scan</span></button></div>
     <label>Description</label><div className="text-field"><input required value={description} onChange={e=>setDescription(e.target.value)} aria-label="Description"/><span className="optional">Shown to payer</span></div>
     {authRequired&&<div className="api-key-field"><label htmlFor="dashboard-api-key">API key</label><input id="dashboard-api-key" type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="sk_live_…"/><small>Stored only for this browser session.</small></div>}{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="primary" type="submit" disabled={submitting}>{submitting?'Creating request…':'Create payment request'} <ArrowRight size={18}/></button></form>
   </div>
   <div className="preview-panel"><div className="panel-heading"><div><span className="step">02</span><h2>Shared obligation</h2></div><span className={payment?'status active':'status'}><i/> {payment?.status==='paid'?'Paid':payment?'Awaiting payment':'Ready'}</span></div>
    {!payment?<div className="empty-state"><div className="orbit"><CircleDollarSign size={38}/></div><h3>Ready when you are</h3><p>Your human and agent payment interfaces will appear here from the same request.</p><div className="empty-lines"><i/><i/><i/></div></div>:
    <div className="payment-result"><div className="request-summary"><div><small>PAYMENT REQUEST</small><strong>{payment.amount} <span>USDC</span></strong><p>{payment.description}</p></div><div className="request-id">{payment.id}</div></div>
     <div className={payment.interfaces?.x402?'channel-grid':'channel-grid human-only'}><article><header><span className="channel-number"><QrCode size={17}/></span><div><strong>Human</strong><small>Solana Pay</small></div></header><div className="qr"><QRCodeSVG value={solanaPayUrl} size={146} bgColor="#fffdf9" fgColor="#17211a"/></div><button onClick={()=>copy('link',solanaPayUrl)}><Copy size={15}/>{copied==='link'?'Copied!':'Copy payment link'}</button></article>
      {payment.interfaces?.x402&&<article><header><span className="channel-number agent"><Bot size={17}/></span><div><strong>Agent</strong><small>x402 v2 · exact</small></div></header><div className="code-card"><span>GET</span><code>/pay/{payment.id}</code><hr/><small>{payment.status==='paid'?'200 RESOURCE UNLOCKED':'402 PAYMENT REQUIRED'}</small><p>payTo: {compact(payment.recipient)}<br/>amount: {payment.amount} USDC<br/>network: {developerMode?payment.networkId:payment.network==='devnet'?'Solana Devnet':'Solana Mainnet'}</p></div><button onClick={()=>copy('endpoint',`${location.origin}/pay/${payment.id}`)}><Copy size={15}/>{copied==='endpoint'?'Copied!':'Copy endpoint'}</button></article>}</div>
     <div className={payment.monitoringError?'settlement monitoring-failed':'settlement'}><CheckCircle2 size={19}/><div><strong>{payment.status==='paid'?'Settlement confirmed':payment.monitoringError?'RPC monitoring unavailable':'One settlement state'}</strong><small>{payment.status==='paid'?`Receipt created · ${compact(payment.signature??'confirmed')}`:payment.monitoringError?'The payment remains safe; Salmon Pay will retry the blockchain check.':payment.interfaces?.x402?'RPC monitoring and x402 resolve to the same receipt and webhook event.':'RPC monitoring validates the onchain transfer and creates one receipt.'}</small></div><b>{payment.status==='paid'?'Confirmed':payment.monitoringError?'Retrying':'Monitoring'} <i/></b></div></div>}
   </div>
  </section>
  {scannerOpen&&<div className="scanner-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setScannerOpen(false)}}><section className="scanner-dialog" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><header><div><small>Solana recipient</small><h2 id="scanner-title">Scan wallet QR</h2></div><button type="button" onClick={()=>setScannerOpen(false)} aria-label="Close scanner"><X size={20}/></button></header><div className="camera-frame"><video ref={videoRef} muted playsInline/ ><span className="scan-corners"/></div><p>{scannerError||'Point the camera at a Solana wallet address or Solana Pay QR.'}</p>{scannerError&&<button className="scanner-retry" type="button" onClick={()=>{setScannerError('');setScannerOpen(false);window.setTimeout(()=>setScannerOpen(true),0)}}><RotateCw size={16}/>Try camera again</button>}</section></div>}
  <section className="principles"><div><span>01</span><h3>API first</h3><p>Everything in the dashboard is available as a clean HTTP resource.</p></div><div><span>02</span><h3>Non-custodial</h3><p>Funds move directly to your Solana wallet. Salmon never holds them.</p></div><div><span>03</span><h3>Protocol native</h3><p>Solana Pay for people. x402 v2 for software. Standard USDC settlement.</p></div></section>
  <footer><span>Salmon Pay · Solana Mainnet</span><label className="developer-toggle"><input type="checkbox" checked={developerMode} onChange={event=>{const enabled=event.target.checked;setDeveloperMode(enabled);localStorage.setItem('salmon_developer_mode',String(enabled));if(!enabled)setNetwork('mainnet-beta')}}/><span aria-hidden="true"/><b>Developer mode</b></label><span>Solana Pay <i>×</i> x402 v2 <i>×</i> USDC</span></footer>
 </main>
}
