import type { PaymentRequest } from './domain';
export type TransferMatch={confirmed:boolean;signature?:string;payer?:string};
export interface RpcAdapter{findTransfer(payment:PaymentRequest):Promise<TransferMatch>}
export interface FacilitatorAdapter{supported():Promise<unknown>;verify(payload:unknown,requirements:unknown):Promise<{isValid:boolean;payer?:string;invalidReason?:string}>;settle(payload:unknown,requirements:unknown):Promise<{success:boolean;transaction?:string;payer?:string;errorReason?:string;errorMessage?:string}>}
type RpcResponse<T>={result?:T;error?:{message:string}};
type TokenBalance={mint:string;owner?:string;uiTokenAmount?:{amount?:string}};
type AccountKey=string|{pubkey:string};
type ParsedTransaction={meta?:{err?:unknown;preTokenBalances?:TokenBalance[];postTokenBalances?:TokenBalance[]};transaction?:{message?:{accountKeys?:AccountKey[]}}};
export class SolanaJsonRpcAdapter implements RpcAdapter{constructor(private rpcUrls:string[]){}private async call<T>(method:string,params:unknown[]){const errors:string[]=[];for(const rpcUrl of this.rpcUrls){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);const json=await response.json() as RpcResponse<T>;if(json.error)throw new Error(json.error.message);return json.result}catch(error){errors.push(`${new URL(rpcUrl).host}: ${error instanceof Error?error.message:'request failed'}`)}finally{clearTimeout(timeout)}}throw new Error(`All RPC endpoints failed (${errors.join('; ')})`)}async findTransfer(payment:PaymentRequest){const signatures=await this.call<Array<{signature:string;err:unknown;confirmationStatus?:string}>>('getSignaturesForAddress',[payment.reference,{limit:12,commitment:'finalized'}])??[];for(const item of signatures){if(item.err)continue;const tx=await this.call<ParsedTransaction>('getTransaction',[item.signature,{commitment:'finalized',encoding:'jsonParsed',maxSupportedTransactionVersion:0}]);if(!tx||tx.meta?.err)continue;const sum=(balances:TokenBalance[]|undefined)=>balances?.filter(balance=>balance.mint===payment.assetMint&&balance.owner===payment.recipient).reduce((total,balance)=>total+BigInt(balance.uiTokenAmount?.amount??'0'),0n)??0n;if(sum(tx.meta?.postTokenBalances)-sum(tx.meta?.preTokenBalances)===BigInt(payment.amountAtomic)){const first=tx.transaction?.message?.accountKeys?.[0];return {confirmed:true,signature:item.signature,payer:typeof first==='string'?first:first?.pubkey}}}return {confirmed:false}}}
let facilitatorFailures=0,circuitOpenUntil=0;
export class HttpFacilitatorAdapter implements FacilitatorAdapter{constructor(private baseUrl:string,private bearer?:string){}private async call(path:string,body?:unknown,retrySafe=false){if(Date.now()<circuitOpenUntil)throw new Error('Facilitator circuit is temporarily open');const attempts=retrySafe?2:1;for(let attempt=0;attempt<attempts;attempt++){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${this.baseUrl}${path}`,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(this.bearer?{authorization:`Bearer ${this.bearer}`}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});const json=await response.json();if(!response.ok)throw new Error(`Facilitator ${response.status}: ${JSON.stringify(json)}`);facilitatorFailures=0;return json}catch(error){facilitatorFailures++;if(facilitatorFailures>=5)circuitOpenUntil=Date.now()+30000;if(attempt+1===attempts)throw error}finally{clearTimeout(timeout)}}throw new Error('Facilitator unavailable')}supported(){return this.call('/supported',undefined,true)}verify(paymentPayload:unknown,paymentRequirements:unknown){return this.call('/verify',{x402Version:2,paymentPayload,paymentRequirements},true)}settle(paymentPayload:unknown,paymentRequirements:unknown){return this.call('/settle',{x402Version:2,paymentPayload,paymentRequirements},false)}}
