import { NETWORKS,X402_DEVNET_FEE_PAYER } from './config';
import type { Network,PaymentChannel,PaymentRequest,Receipt } from './domain';
import { isSolanaPublicKey,randomPublicKey } from './base58';
import { SolanaJsonRpcAdapter } from './adapters';
import { emitPaymentPaid } from './webhook-service';
import { parseUsdcAmount } from './money';
import { getRecord,listRecords,putPaymentIdempotently,putRecord,settlePaymentAtomically } from './repository';
import { assertMainnetReady } from './production-readiness';

const id=(prefix:string)=>`${prefix}_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`;
async function digest(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function createPayment(input:{amount:string;recipient:string;description:string;network?:Network;expiresInSeconds?:number},idempotencyKey?:string){const network=input.network??'mainnet-beta';if(network==='mainnet-beta')assertMainnetReady();const {display,atomic}=parseUsdcAmount(input.amount);if(!isSolanaPublicKey(input.recipient))throw new Error('recipient must be a valid Solana address');if(!input.description?.trim())throw new Error('description is required');const ttl=input.expiresInSeconds??86400;if(![3600,86400,604800].includes(ttl))throw new Error('expiration must be 1 hour, 24 hours, or 7 days');if(idempotencyKey!==undefined&&(idempotencyKey.length<8||idempotencyKey.length>200))throw new Error('Idempotency-Key must contain 8 to 200 characters');const now=new Date(),p:PaymentRequest={id:id('pay'),amount:display,amountAtomic:atomic,asset:'USDC',assetMint:NETWORKS[network].usdcMint,network,networkId:NETWORKS[network].caip2,recipient:input.recipient,description:input.description.trim(),reference:randomPublicKey(),status:'pending',createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+ttl*1000).toISOString()};if(idempotencyKey){const canonical=JSON.stringify({amount:display,recipient:p.recipient,description:p.description,network,ttl});return await putPaymentIdempotently<PaymentRequest>(await digest(idempotencyKey),await digest(canonical),p.id,p) as PaymentRequest}await putRecord('payments',p.id,p);return p}
export async function getPayment(id:string){const p=await getRecord<PaymentRequest>('payments',id);if(p&&p.status==='pending'&&Date.parse(p.expiresAt)<Date.now()){p.status='expired';await putRecord('payments',id,p)}return p}
export async function listPayments(){return (await listRecords<PaymentRequest>('payments')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export function solanaPayUrl(p:PaymentRequest){const q=new URLSearchParams({amount:p.amount,'spl-token':p.assetMint,reference:p.reference,label:'Salmon Pay',message:p.description,memo:p.id});return `solana:${p.recipient}?${q}`}
export function requirements(p:PaymentRequest){return {scheme:'exact',network:p.networkId,asset:p.assetMint,amount:p.amountAtomic,payTo:p.recipient,maxTimeoutSeconds:60,extra:{name:'USDC',version:'2',...(p.network==='devnet'?{feePayer:X402_DEVNET_FEE_PAYER}:{})}} as const}
export async function markPaymentPaid(p:PaymentRequest,input:{signature:string;payer?:string;channel:PaymentChannel}){if(p.status==='paid')return getRecord<Receipt>('receipts',p.id);const paidAt=new Date().toISOString(),paidPayment:PaymentRequest={...p,status:'paid',signature:input.signature,payer:input.payer,channel:input.channel,paidAt},receipt:Receipt={id:`rcpt_${p.id.slice(4)}`,paymentRequestId:p.id,amount:p.amount,asset:'USDC',network:p.network,recipient:p.recipient,signature:input.signature,payer:input.payer,paidAt,channel:input.channel};const settled=await settlePaymentAtomically(p.id,paidPayment,receipt);if(!settled)return getRecord<Receipt>('receipts',p.id);Object.assign(p,paidPayment);await emitPaymentPaid({paymentRequest:paidPayment,receipt});return receipt}
export async function refreshHumanPayment(p:PaymentRequest){if(p.status!=='pending'||Date.now()-Date.parse(p.lastCheckedAt??'1970-01-01')<3000)return p;p.lastCheckedAt=new Date().toISOString();await putRecord('payments',p.id,p);const rpc=new SolanaJsonRpcAdapter(NETWORKS[p.network].rpcUrls);try{const match=await rpc.findTransfer(p);p.monitoringError=undefined;if(match.confirmed&&match.signature)await markPaymentPaid(p,{signature:match.signature,payer:match.payer,channel:'solana-pay'});else await putRecord('payments',p.id,p)}catch(error){p.monitoringError=error instanceof Error?error.message:'RPC check failed';await putRecord('payments',p.id,p);throw error}return p}
export async function updatePendingAmount(paymentId:string,input:unknown){const p=await getPayment(paymentId);if(!p)throw new Error('Payment request not found');if(p.status!=='pending')throw new Error('Only pending payment requests can be updated');const {display,atomic}=parseUsdcAmount(input);p.amount=display;p.amountAtomic=atomic;await putRecord('payments',p.id,p);return p}
